export const COUNTRIES = [
  { label: "🌎 International", value: "international" },
  { label: "🇦🇷 Argentina", value: "argentina" },
  { label: "🇧🇪 Belgium", value: "belgium" },
  { label: "🇧🇷 Brazil", value: "brazil" },
  { label: "🇨🇿 Czech Republic", value: "czech-republic" },
  { label: "🇩🇰 Denmark", value: "denmark" },
  { label: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England", value: "england" },
  { label: "🇫🇷 France", value: "france" },
  { label: "🇩🇪 Germany", value: "germany" },
  { label: "🇮🇹 Italy", value: "italy" },
  { label: "🇲🇽 Mexico", value: "mexico" },
  { label: "🇳🇱 Netherlands", value: "netherlands" },
  { label: "🇵🇱 Poland", value: "poland" },
  { label: "🇵🇹 Portugal", value: "portugal" },
  { label: "🇪🇸 Spain", value: "spain" },
  { label: "🇨🇭 Switzerland", value: "switzerland" },
  { label: "🇹🇷 Turkey", value: "turkey" },
  { label: "🇺🇸 United States", value: "usa" },
];
