export const TOP_LEAGUES = [
  { label: "National Team", value: "national-team" },
  { label: "Premier League", value: "premier-league" },
  { label: "Italian Serie A", value: "serie-a" },
  { label: "German Bundesliga", value: "bundesliga" },
  { label: "Spanish La Liga", value: "la-liga" },
  { label: "French Ligue 1", value: "ligue-1" },
  { label: "Brazilian Serie A", value: "brasileirao" },
  { label: "Portuguese Primeira Liga", value: "primeira-liga" },
  { label: "Belgian Pro League", value: "pro-league" },
  { label: "Major League Soccer", value: "mls" },
  { label: "English Championship", value: "championship" },
  { label: "Liga Professional Argentina", value: "liga-argentina" },
  { label: "Danish Superligaen", value: "superligaen" },
  { label: "Dutch Eredivisie", value: "eredivisie" },
  { label: "Liga MX", value: "liga-mx" },
  { label: "Czech First League", value: "czech-league" },
  { label: "Polish Ekstraklasa", value: "ekstraklasa" },
  { label: "German Bundesliga Zwei", value: "bundesliga-2" },
  { label: "Turkish Super Lig", value: "super-lig" },
  { label: "Italian Serie B", value: "serie-b" },
  { label: "Swiss Super League", value: "swiss-league" },
];
